name: 'Test Evaluate'
description: 'Evaluate action '
author: 'Gabriel'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  username:
    description: 'The username to authenticate with IQ Server'
    required: true
  password:
    description: 'The password to authenticate with IQ Server'
    required: true
  application-id:
    description: 'The IQ Server application ID'
    required: true
  
# Define your outputs here.
outputs:
  scan-id:
    value: ${{ steps.test.outputs.scan-id }}
    description: 'Scan id result of the run operation'
  report-url:
    value: ${{ steps.test.outputs.report-url }}
    description: 'Use this link to navigate directly to the report'

runs:
  using: "composite"
  steps:

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
