name: Evaluate Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  iq-evaluation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: IQ Evaluate
      id: evaluate
      uses: sonatype/actions/evaluate@v1.0.6-beta
      with:
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        application-id: testdata
        result-file: result
        keep-scan-file: true
        scan-targets: pom.xml
        sarif-file: 'my-file.sarif'
        upload-sarif-file: true

    - name: Fetch SBOM
      uses: sonatype/actions/fetch-sbom@v1
      if: ( success() || failure() ) && steps.evaluate.outputs.scan-id 
      with:
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        application-id: testdata
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        sbom-standard: spdx
        sbom-format: json
        sbom-version: 2.3
        push-dependency-graph: true
