name: Evaluate Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  iq-evaluation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: print token
      id: printToken
      run: echo "${{ github.token }}"
    
    # - name: IQ Evaluate
    #   id: evaluate
    #   uses: sonatype/actions/evaluate@v1.0.6-beta
    #   with:
    #     username: ${{ secrets.SSA_USERNAME }}
    #     password: ${{ secrets.SSA_PASSWORD }}
    #     iq-server-url: https://sonatype.sonatype.app/platform
    #     application-id: testdata
    #     result-file: result
    #     keep-scan-file: true
    #     scan-targets: pom.xml
    #     debug: false
    #     ignore-system-errors: true
    #     ignore-scanning-errors: true
    #     # sarif-file: myfile.sarif
    #     upload-sarif-file: true

    - name: Setup IQ CLI Action
      id: setup-iq-cli
      uses: sonatype/actions/setup-iq-cli@v1.0.6-beta
      with:
        iq-cli-version: 'latest'

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run IQ CLI Action
      id: run-iq-cli
      uses: sonatype/actions/run-iq-cli@v1.0.6-beta
      with:
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        iq-server-url: https://sonatype.sonatype.app/platform
        application-id: testdata
        result-file: result
        keep-scan-file: true
        scan-targets: pom.xml
        debug: false
        ignore-system-errors: true
        ignore-scanning-errors: true
        sarif-file: myfile.sarif
        
    - name: showing resulting file
      if: ( success() || failure() )
      run: |
        echo ${{ steps.run-iq-cli.outputs.sarif-file }}
        cat ${{ steps.run-iq-cli.outputs.sarif-file }}
        ls -la 
    
    # - name: Fetch SBOM
    #   uses: sonatype/actions/fetch-sbom@v1
    #   if: ( success() || failure() ) && steps.evaluate.outputs.scan-id 
    #   with:
    #     scan-id: ${{ steps.evaluate.outputs.scan-id }}
    #     application-id: testdata
    #     sbom-standard: spdx
    #     sbom-format: json
    #     sbom-version: 2.3
    #     iq-server-url: https://sonatype.sonatype.app/platform
    #     username: ${{ secrets.SSA_USERNAME }}
    #     password: ${{ secrets.SSA_PASSWORD }}
    #     push-dependency-graph: true
