name: RunIQ Workflow

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  iq-evaluation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup IQ CLI Action
      id: setup-iq-cli
      uses: sonatype/actions/setup-iq-cli@v1.1.2-beta
      with:
        iq-cli-version: 'latest'
  
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: '20.x'
    
    - name: Install Production Node Dependencies
      run: npm install --prod
  
    - name: Run IQ CLI Action
      id: run-iq-cli
      uses: sonatype/actions/run-iq-cli@v1.1.2-beta
      with:
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        application-id: testdata
        result-file: result
        keep-scan-file: true
        scan-targets: package.json
        debug: false
        sarif-file: myfile.sarif
   
    - name: Showing resulting file
      if: steps.run-iq-cli.outputs.sarif-file && ( success() || failure() )
      run: |
        cat ${{ steps.run-iq-cli.outputs.sarif-file }}
        ls -la
    
